# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "region" {
    default = "us-east-2"
}

variable "instance_type" {}
variable "mensagem" {}
variable "alb_name" {}
variable "instance_security_group_name" {}
variable "alb_security_group_name" {}
variable "asg_desired_capacity" {
    type = number
}
variable "asg_min_size" {
    type = number
}
variable "asg_max_size" {
    type = number
}
